In [ ]:
#ERP Data Analytics on TrueERP Purchase Bills Data
This Notebook performs data cleaning, data filtering, and data analysis on purchase bill data exported from the TrueERP system using Python Pandas

In [2]:
import pandas as pd

In [3]:
#Data Loading: The Dataset ised in this analysis is a CSV export of purchase bills from the TrueERP system.

df = pd.read_csv("AllPurchaseBills.csv")

In [4]:
df.head()

,Supplier Name,Invoice No,Invoice Date,Total Amount (),Paid Amount (),Balance Amount (),TDS
0,CASH MEMO,MUSKAN BIRYANI,01-04-2025,840.0,840.0,0.0,0.0
1,SUPERWELD SOURCES PVT LTD,110/2526,01-04-2025,45953.0,45953.0,0.0,0.0
2,S.S. SALES & SERVICES,SS25-26/0001,01-04-2025,10053.6,0.0,10053.6,0.0
3,MAHARASHTRA HARDWARE,20059,01-04-2025,2714.0,2714.0,0.0,0.0
4,MAHARASHTRA HARDWARE,20077,02-04-2025,472.0,472.0,0.0,0.0

In [5]:
#Data Understanding: This step helps to understand the structure, data types, and overall quality of the ERP dataset.
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Supplier Name      285 non-null    object
 1   Invoice No         284 non-null    object
 2   Invoice Date       285 non-null    object
 3   Total Amount ()    285 non-null    float64
 4   Paid Amount ()     285 non-null    float64
 5   Balance Amount ()  285 non-null    float64
 6   TDS                285 non-null    float64
dtypes: float64(4), object(3)
memory usage: 15.7+ KB

       Total Amount ()  Paid Amount ()  Balance Amount ()    TDS
count       285.000000      285.000000         285.000000  285.0
mean      27683.935333     8059.403439       19596.581018    0.0
std       74067.105593    44419.299378       61906.578684    0.0
min           0.000000        0.000000       -2914.500000    0.0
25%         960.000000        0.000000           0.000000    0.0
50%        3400.000000        0.000000         500.000000    0.0
75%       19366.000000     2183.000000        7080.000000    0.0
max      664784.860000   664784.860000      664784.860000    0.0

In [6]:
#Data Cleaning: Data Cleaning is performed to handle misiing values, correct data types, and standardize column names to make the dataset analysis-ready.

#check missing values
df.isna().sum()

Supplier Name        0
Invoice No           1
Invoice Date         0
Total Amount ()      0
Paid Amount ()       0
Balance Amount ()    0
TDS                  0
dtype: int64

In [7]:
# Invoice Number is a mandotory field in ERP System.

#handle missing invoice numbers
df["Invoice No"] = df["Invoice No"].fillna("UNKNOWN")

In [8]:
#Invoice date is converted into datetime format to enable time-based analysis.

#Convert Invoice Date to Date Format
df["Invoice Date"] = pd.to_datetime(df["Invoice Date"], dayfirst=True)

In [9]:
#Column names are standardized for easier referencing and consistency.

#Standaedize Column Names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("()","",regex=False)
)
df.columns

Index(['supplier_name', 'invoice_no', 'invoice_date', 'total_amount_',
       'paid_amount_', 'balance_amount_', 'tds'],
      dtype='object')

In [10]:
#Data Filtering is applied to extract meaningful subsets of data based on business conditions.

#data filtering


#identify high balue purchase bills
high_value_bills = df[df["total_amount_"] > 50000]
high_value_bills[["supplier_name", "total_amount_"]]

                            supplier_name  total_amount_
11                 GEETA SURFACE COATINGS      110448.00
20                MAITRI METALS PVT. LTD.      159005.00
28   EMPLOYEE PROVIDEND FUND ORGANISATION       57983.00
33                  EQUIFAB INDIA PVT.LTD      168504.00
34                  EQUIFAB INDIA PVT.LTD      224436.00
50          MASTERLUBE ENGINEERS PVT. LTD       77993.28
68                            MAHAVITARAN       65360.00
69                    SHEKASA ENGINEERING       55660.60
91                  EQUIFAB INDIA PVT.LTD      382320.00
92                  EQUIFAB INDIA PVT.LTD       93220.00
125                GEETA SURFACE COATINGS       57348.00
138                 EQUIFAB INDIA PVT.LTD      210512.00
143                 SANSKRUTI ENTERPRISES       84039.60
144                   SHANTANU INDUSTRIES      664784.86
147               MAITRI METALS PVT. LTD.       91025.20
158           VENUS DATA PRODUCTS PVT LTD      172899.50
172                   ESSTECH ENGINEERING       54404.00
176                           MAHAVITARAN       73590.00
177             SWASTIK ENGINEERING WORKS       73042.00
189              ADITYA STAINLESS (INDIA)       64841.00
204  EMPLOYEE PROVIDEND FUND ORGANISATION       61563.00
214          EAGLE BURGMANN INDIA PVT LTD      178635.48
215                 EQUIFAB INDIA PVT.LTD       75260.40
217                 EQUIFAB INDIA PVT.LTD       70092.00
218                 EQUIFAB INDIA PVT.LTD      165436.00
223                 EQUIFAB INDIA PVT.LTD       53808.00
240                     TUV INDIA PVT LTD      183873.50
241                             CASH MEMO      206500.00
259                GEETA SURFACE COATINGS       57348.00
264                 EQUIFAB INDIA PVT.LTD      188160.00
265                 EQUIFAB INDIA PVT.LTD      268800.00
266                 EQUIFAB INDIA PVT.LTD      206976.00
267                 EQUIFAB INDIA PVT.LTD       92960.00
272                 EQUIFAB INDIA PVT.LTD      100352.00
273                 EQUIFAB INDIA PVT.LTD      330624.00
275                 SANSKRUTI ENTERPRISES       91190.40
277                     SHREE METAL INDIA       75082.69
278                   SHANTANU INDUSTRIES      664784.86

In [11]:
#supplier specific filtering

df[df["supplier_name"] == "MAHARASHTRA HARDWARE"]

,supplier_name,invoice_no,invoice_date,total_amount_,paid_amount_,balance_amount_,tds
3,MAHARASHTRA HARDWARE,20059,2025-04-01,2714.00,2714.00,0.00,0.0
4,MAHARASHTRA HARDWARE,20077,2025-04-02,472.00,472.00,0.00,0.0
5,MAHARASHTRA HARDWARE,20083,2025-04-02,343.38,343.38,0.00,0.0
15,MAHARASHTRA HARDWARE,20114,2025-04-05,1416.00,1416.00,0.00,0.0
55,MAHARASHTRA HARDWARE,20208,2025-04-11,495.60,495.60,0.00,0.0
76,MAHARASHTRA HARDWARE,20266,2025-04-16,778.80,778.80,0.00,0.0
103,MAHARASHTRA HARDWARE,20346,2025-04-21,339.84,0.00,339.84,0.0
187,MAHARASHTRA HARDWARE,CASH MEMO,2025-05-09,210.00,210.00,0.00,0.0
224,MAHARASHTRA HARDWARE,CASH MEMO,2025-05-19,80.00,80.00,0.00,0.0
225,MAHARASHTRA HARDWARE,6,2025-05-19,5400.00,5400.00,0.00,0.0
251,MAHARASHTRA HARDWARE,20759,2025-05-24,1016.69,0.00,1016.69,0.0
270,MAHARASHTRA HARDWARE,20875,2025-05-29,560.50,0.00,560.50,0.0

In [12]:
#Data Analysis: This Section performs analytical operations to derive insights from the cleaned and filtered ERP data

#Total Purchase, Paid, and Oustanding Amount
total_purchase = df["total_amount_"].sum()
total_paid = df["paid_amount_"].sum()
total_balance = df["balance_amount_"].sum()

total_purchase, total_paid, total_balance

(np.float64(7889921.57), np.float64(2296929.98), np.float64(5585025.59))

In [13]:
#Monthly Purchase Trend Analysis
monthly_purchase = (
    df.groupby(df["invoice_date"].dt.to_period("M"))["total_amount_"]
    .sum()
    .reset_index()
)

monthly_purchase

  invoice_date  total_amount_
0      2025-04     3780146.07
1      2025-05     4052356.50
2      2025-06       57419.00

In [14]:
#Top 10 Suppliers by Purchase Value
top_suppliers = (
    df.groupby("supplier_name")["total_amount_"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_suppliers

supplier_name
EQUIFAB INDIA PVT.LTD           2796896.40
SHANTANU INDUSTRIES             1329569.72
GEETA SURFACE COATINGS           400842.00
MAITRI METALS PVT. LTD.          372354.90
CASH MEMO                        244048.40
TUV INDIA PVT LTD                214553.50
EAGLE BURGMANN INDIA PVT LTD     178635.48
VENUS DATA PRODUCTS PVT LTD      177899.16
SANSKRUTI ENTERPRISES            175230.00
MAHAVITARAN                      138950.00
Name: total_amount_, dtype: float64

In [15]:
#Payment Effeciency Analysis
df["payment_ratio"] = df["paid_amount_"] / df["total_amount_"]
df[["supplier_name", "payment_ratio"]].head()

               supplier_name  payment_ratio
0                  CASH MEMO            1.0
1  SUPERWELD SOURCES PVT LTD            1.0
2      S.S. SALES & SERVICES            0.0
3       MAHARASHTRA HARDWARE            1.0
4       MAHARASHTRA HARDWARE            1.0

In [16]:
#TDS Analysis
total_tds = df["tds"].sum()
total_tds

np.float64(0.0)

In [17]:
#Export Cleaned Dataset: The Clean Dataset is reported for reporting and dashboard creation.

df.to_csv("cleaned_purchase_bills.csv", index=False)

In [ ]:
## Conclusion

#The TrueERP purchase bills data was successfully cleaned, filtered, and analyzed using Python Pandas. The analysis provided insights into purchase trends,
#supplier dependency, outstanding liabilities, and tax deductions, demonstrating how ERP data supports data-driven decision-making.